apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  labels:
    app: devops-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo
          image: ghcr.io/wu-yi-ru/devops-demo:46d5d5381538e44c593b9ae7049d9b7eb83166ff
          imagePullPolicy: Always
          ports:
            - containerPort: 6163
          readinessProbe:
            httpGet:
              path: /health
              port: 6163
            periodSeconds: 5
