apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  labels:
    app: devops-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo
          image: ghcr.io/wu-yi-ru/devops-demo:c3f3872545152145cb04d1c5e3eec8edeb82a686
          imagePullPolicy: Always
          ports:
            - containerPort: 6163
          readinessProbe:
            httpGet:
              path: /health
              port: 6163
            periodSeconds: 5
